#pragma once
// The in-game debug view of ONE traced timing (AUDIT §11; docs/TIMING_SOLVER_V2.md §2.12, V2-D12):
// what the overlay draws and the panel / Session tab print for the last traced input.
//
// Source: the engine's last trace (core/solver/trace View, exposed by solver::oracle::lastTrace):
// exactly what its `GPRL trace:` lines printed - the header (input #, press / release, seq,
// attempt time, tick, x, percent, gamemode, speed, gravity, mini, the LOCAL window, the
// SEQUENCE-ADJUSTED window, the hold range; the window texts are generated by the engine from the
// timing_result payload's canonical ms, AUDIT §9) and the trajectories by role:
//   reference (the control = the real run), earliest-valid, early-invalid (just before the
//   earliest valid shift), latest-valid, late-invalid (just after the latest valid shift), and
//   "sa-..." for the sequence-adjusted edges (the adaptation in brackets)
// each with its death (killer id / type / rect, the clone's hitbox, later inputs applied first,
// frozen-world extension) when it died.
//
// This file turns that into drawable paths (world coordinates of the object layer) and short text
// lines, including WHY an invalid trajectory failed (self / downstream / frozen death pause, §2.3).
// The mod only DRAWS it (src/Hud); nothing here touches physics.
//
// PURE C++20 (no Geode includes); host-tested in tests/trace_view_tests.cpp.
#include <cstdint>
#include <cstdio>
#include <string>
#include <utility>
#include <vector>

#include "timing_units.hpp"
#include "trace.hpp"

namespace gprl::solver::trace_view {

/// The trajectories of §2.12 (local block, then the sequence-adjusted block).
enum class Role : uint8_t {
    Reference, EarliestValid, EarlyInvalid, LatestValid, LateInvalid,
    SaEarliestValid, SaEarlyInvalid, SaLatestValid, SaLateInvalid,
    Other,
};

/// Role of a trace line's role text ("early-invalid", "sa-late-invalid (pair)", ...).
inline Role roleOf(std::string const& name) {
    auto is = [&](char const* prefix) { return name.rfind(prefix, 0) == 0; };
    if (is("sa-earliest-valid")) return Role::SaEarliestValid;
    if (is("sa-early-invalid")) return Role::SaEarlyInvalid;
    if (is("sa-latest-valid")) return Role::SaLatestValid;
    if (is("sa-late-invalid")) return Role::SaLateInvalid;
    if (is("reference")) return Role::Reference;
    if (is("earliest-valid")) return Role::EarliestValid;
    if (is("early-invalid")) return Role::EarlyInvalid;
    if (is("latest-valid")) return Role::LatestValid;
    if (is("late-invalid")) return Role::LateInvalid;
    return Role::Other;
}
constexpr bool invalidRole(Role r) {
    return r == Role::EarlyInvalid || r == Role::LateInvalid || r == Role::SaEarlyInvalid || r == Role::SaLateInvalid;
}
constexpr bool validRole(Role r) {
    return r == Role::EarliestValid || r == Role::LatestValid || r == Role::SaEarliestValid || r == Role::SaLatestValid;
}
constexpr bool sequenceRole(Role r) {
    return r == Role::SaEarliestValid || r == Role::SaEarlyInvalid || r == Role::SaLatestValid || r == Role::SaLateInvalid;
}

struct Point {
    float x = 0.f, y = 0.f;
};

struct Path {
    Role role = Role::Other;
    std::string name;                // the role text as the log printed it ("sa-late-invalid (pair)")
    double shiftFrames = 0.0;        // signed, 240 Hz ticks (fractional with CBF)
    double shiftMs = 0.0;            // the same shift in ms (timing_units, one conversion)
    std::vector<Point> points;       // the clone's position at the end of every recorded step
    bool passed = false;
    bool capped = false;             // the recording hit maxTraceSteps
    trace::TraceDeath death;         // death.died: where / on what / after how many later inputs
};

struct View {
    bool any = false;
    int serial = 0;                  // the engine's trace serial this view was built from
    trace::Header header;            // input #, type, seq, t, tick, x, percent, mode, speed, gravity, mini, windows, hold
    std::vector<Path> paths;         // in the log's order: reference first
};

/// A display View of the engine's last trace (serial 0 = nothing traced: any = false).
inline View fromEngine(trace::View const& ev) {
    View v;
    if (ev.serial == 0) return v;
    v.any = true;
    v.serial = ev.serial;
    v.header = ev.header;
    v.paths.reserve(ev.trajectories.size());
    for (auto const& [name, c] : ev.trajectories) {
        Path p;
        p.role = roleOf(name);
        p.name = name;
        p.shiftFrames = c.shiftFrames;
        p.shiftMs = units::framesToMs(c.shiftFrames);   // the one frames -> ms conversion (AUDIT §9)
        p.points.reserve(c.steps.size());
        for (auto const& s : c.steps) p.points.push_back({s.x, s.y});
        p.passed = c.passed;
        p.capped = c.capped;
        p.death = c.death;
        v.paths.push_back(std::move(p));
    }
    return v;
}

/// Why a trajectory failed, in words (AUDIT §11 "reason for invalid result", §2.3 attribution).
inline std::string invalidReason(trace::TraceDeath const& d) {
    if (!d.died) return "not resolved (no death recorded)";
    if (d.extension) return "frozen death pause (extension): the world did not move, the bound is undecidable here";
    if (d.laterInputs >= 1) {
        char buf[160];
        std::snprintf(buf, sizeof buf, "downstream: %d later input%s applied as performed first (not this input alone)", d.laterInputs,
                      d.laterInputs == 1 ? "" : "s");
        return buf;
    }
    if (d.laterInputs == 0) return "self: died before any later input acted";
    return "cause unknown";
}

/// The one-word cause for the summary line.
inline std::string causeWord(trace::TraceDeath const& d) {
    if (!d.died) return "unresolved";
    if (d.extension) return "extension";
    if (d.laterInputs >= 1) return "downstream " + std::to_string(d.laterInputs);
    if (d.laterInputs == 0) return "self";
    return "unknown";
}

/// "died f3518.0 on #1717 type 7 at (4668.2, 262.9) box 30x30" - the death / collision point.
inline std::string deathText(trace::TraceDeath const& d) {
    if (!d.died) return "no death";
    char buf[200];
    if (d.killerId >= 0) {
        std::snprintf(buf, sizeof buf, "died f%.1f on #%d type %d at (%.1f, %.1f) box %.0fx%.0f", d.frame, d.killerId, d.killerType, d.x, d.y,
                      d.boxW, d.boxH);
    }
    else std::snprintf(buf, sizeof buf, "died f%.1f, no object (#-1) at (%.1f, %.1f) box %.0fx%.0f", d.frame, d.x, d.y, d.boxW, d.boxH);
    return buf;
}

/// GD's speed portal label from the header's multiplier (0.5, 1, 2, 3, 4).
inline char const* speedLabel(double speed) {
    if (speed < 0.75) return "slow";
    if (speed < 1.5) return "normal";
    if (speed < 2.5) return "fast";
    if (speed < 3.5) return "faster";
    return "fastest";
}

/// The panel's text, one line each (the overlay colours them: header white, valid trajectories
/// green, invalid ones and their reasons red). Short enough for the in-game panel.
inline std::vector<std::string> panelLines(View const& v) {
    std::vector<std::string> out;
    if (!v.any) return out;
    auto const& h = v.header;
    char buf[256];
    std::snprintf(buf, sizeof buf, "TRACE input #%d %s (seq %lld) | t %.4f s tick %lld | %.3f%% x %.1f", h.inputIndex, h.down ? "press" : "release",
                  static_cast<long long>(h.seq), h.t, static_cast<long long>(h.tick), h.percent, h.x);
    out.emplace_back(buf);
    std::snprintf(buf, sizeof buf, "%s | speed %s (%gx) | gravity %s | mini %s", h.mode.c_str(), speedLabel(h.speed), h.speed,
                  h.flipped ? "flipped" : "normal", h.mini ? "yes" : "no");
    out.emplace_back(buf);
    out.push_back("local (fixed-sequence) " + (h.local.empty() ? std::string("-") : h.local));
    out.push_back("sequence-adjusted " + (h.sequence.empty() ? std::string("- (not measured)") : h.sequence));
    out.push_back("hold " + (h.hold.empty() ? std::string(h.down ? "- (press)" : "- (press unknown)") : h.hold));
    for (auto const& p : v.paths) {
        if (p.role == Role::Reference) continue;
        std::snprintf(buf, sizeof buf, "%s shift %+g (%+.2f ms): ", p.name.c_str(), p.shiftFrames, p.shiftMs);
        std::string line = buf;
        if (invalidRole(p.role)) {
            out.push_back(line + deathText(p.death));
            out.push_back("  why: " + invalidReason(p.death));
        }
        else out.push_back(line + (p.passed || !p.death.died ? std::string("passed") : deathText(p.death)));
    }
    return out;
}

/// One line for the popup's Session tab: "Trace #47 press t 14.5833 s 13.042% wave | local ... |
/// seq ... | early-invalid self, late-invalid downstream 2".
inline std::string summaryLine(View const& v) {
    if (!v.any) return {};
    auto const& h = v.header;
    char buf[160];
    std::snprintf(buf, sizeof buf, "Trace #%d %s t %.4f s %.3f%% %s", h.inputIndex, h.down ? "press" : "release", h.t, h.percent, h.mode.c_str());
    std::string s = buf;
    s += " | local " + (h.local.empty() ? std::string("-") : h.local);
    s += " | seq " + (h.sequence.empty() ? std::string("-") : h.sequence);
    std::string why;
    for (auto const& p : v.paths) {
        if (!invalidRole(p.role) || sequenceRole(p.role)) continue;
        why += (why.empty() ? " | " : ", ") + p.name + " " + causeWord(p.death);
    }
    return s + why;
}

}  // namespace gprl::solver::trace_view
